name: Autograding Tests
on:
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]' && github.actor != 'jacobsteffenBYU'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12.6
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install pytest pytest-subtests 'black<=22.3.0' 'tomli>=1.1.0' 'timeout-decorator~=0.5.0'
    - name: tests/test_01_input_prompts_list.py
      id: tests-test-01-input-prompts-list-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-01-input-prompts-list
        setup-command: ''
        command: python -m pytest -v tests/test_01_input_prompts_list.py
        timeout: 30
        max-score: 15
    - name: tests/test_02_input_prompts_dictionary.py
      id: tests-test-02-input-prompts-dictionary-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-02-input-prompts-dictionary
        setup-command: ''
        command: python -m pytest -v tests/test_02_input_prompts_dictionary.py
        timeout: 30
        max-score: 15
    - name: tests/test_03_printed_messages_list.py
      id: tests-test-03-printed-messages-list-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-03-printed-messages-list
        setup-command: ''
        command: python -m pytest -v tests/test_03_printed_messages_list.py
        timeout: 30
        max-score: 15
    - name: tests/test_04_printed_messages_dictionary.py
      id: tests-test-04-printed-messages-dictionary-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-04-printed-messages-dictionary
        setup-command: ''
        command: python -m pytest -v tests/test_04_printed_messages_dictionary.py
        timeout: 30
        max-score: 15
    - name: tests/test_05_list_properly_updated.py
      id: tests-test-05-list-properly-updated-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-05-list-properly-updated
        setup-command: ''
        command: python -m pytest -v tests/test_05_list_properly_updated.py
        timeout: 30
        max-score: 15
    - name: tests/test_06_dictionary_properly_updated.py
      id: tests-test-06-dictionary-properly-updated-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-06-dictionary-properly-updated
        setup-command: ''
        command: python -m pytest -v tests/test_06_dictionary_properly_updated.py
        timeout: 30
        max-score: 15
    - name: tests/test_07_sufficient_comments.py
      id: tests-test-07-sufficient-comments-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-07-sufficient-comments
        setup-command: ''
        command: python -m pytest -v tests/test_07_sufficient_comments.py
        timeout: 30
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTS-TEST-01-INPUT-PROMPTS-LIST-PY_RESULTS: ${{steps.tests-test-01-input-prompts-list-py.outputs.result}}
        TESTS-TEST-02-INPUT-PROMPTS-DICTIONARY-PY_RESULTS: ${{steps.tests-test-02-input-prompts-dictionary-py.outputs.result}}
        TESTS-TEST-03-PRINTED-MESSAGES-LIST-PY_RESULTS: ${{steps.tests-test-03-printed-messages-list-py.outputs.result}}
        TESTS-TEST-04-PRINTED-MESSAGES-DICTIONARY-PY_RESULTS: ${{steps.tests-test-04-printed-messages-dictionary-py.outputs.result}}
        TESTS-TEST-05-LIST-PROPERLY-UPDATED-PY_RESULTS: ${{steps.tests-test-05-list-properly-updated-py.outputs.result}}
        TESTS-TEST-06-DICTIONARY-PROPERLY-UPDATED-PY_RESULTS: ${{steps.tests-test-06-dictionary-properly-updated-py.outputs.result}}
        TESTS-TEST-07-SUFFICIENT-COMMENTS-PY_RESULTS: ${{steps.tests-test-07-sufficient-comments-py.outputs.result}}
      with:
        runners: tests-test-01-input-prompts-list-py,tests-test-02-input-prompts-dictionary-py,tests-test-03-printed-messages-list-py,tests-test-04-printed-messages-dictionary-py,tests-test-05-list-properly-updated-py,tests-test-06-dictionary-properly-updated-py,tests-test-07-sufficient-comments-py
